name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get project code
        uses: actions/checkout@v3

      - name: Install Deps
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: build

      - uses: actions/download-artifact@v3
        with:
          name: public

      - name: Display structure of downloaded files
        run: ls -R

