name: Pull Request Workflow

on:
  pull_request:

jobs:
  pr-checks:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Install deps
        run: npm install

      - name: Test
        run: npm run test:unit

      - name: Lint
        run: npm run lint