name: Push Request Workflow

on: push

jobs:
  pr-checks:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Install deps
        run: npm install

      - name: Lint
        run: vue-cli-service lint

      - name: Test
        run: vue-cli-service test:unit