name: Push Workflow

on:
  push:
    branches: [master]
  jobs:
    build:
    runs-on: self-hosted
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          platforms: linux/amd64,linux/arm64/v8
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8
      - name: Build And Push MP Docker Image
        uses: docker/build-push-actions@v3
        with:
          push: false
          tags: user/app:latest