name: Push Request Workflow

on: push

jobs:
  pr-checks:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test